if(NOT DEFINED OPTIONAL_SOURCE OR NOT DEFINED OPTIONAL_DESTINATION)
    message(FATAL_ERROR "OPTIONAL_SOURCE and OPTIONAL_DESTINATION are required")
endif()

if(EXISTS "${OPTIONAL_SOURCE}")
    configure_file("${OPTIONAL_SOURCE}" "${OPTIONAL_DESTINATION}" COPYONLY)
endif()
